; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.31"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[front][version] = "2.4"

projects[module_filter][version] = "2.0-alpha2"

projects[backup_migrate][version] = "3.0"

projects[better_exposed_filters][version] = "3.0-beta4"

projects[ctools][version] = "1.4"

projects[calendar][version] = "3.x-dev"

projects[date][version] = "2.8"

projects[editableviews][version] = "1.0-beta8"

projects[entity][version] = "1.5"

projects[features][version] = "2.2"

projects[field_collection][version] = "1.0-beta7"

projects[logintoboggan][version] = "1.4"

projects[masquerade][version] = "1.0-rc7"

projects[node_export][version] = "3.0"

projects[node_save_redirect][version] = "1.1"

projects[references][version] = "2.1"

projects[rules][version] = "2.7"

*projects[superfish][version] = "1.9"

projects[uuid][version] = "1.0-alpha5"

projects[vars][version] = "2.0-alpha10"

projects[views][version] = "3.8"

projects[video][version] = "2.10"

projects[views_datasource][version] = "1.x-dev"

; Libraries
libraries[superfish][download][type] = "git"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal.git"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][destination] = "libraries"

; Themes
projects[zen][version] = "5.5"

